In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from sklearn.cross_validation import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
%matplotlib notebook

C:\Users\Lau\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
EMEF = pd.read_csv('Dades_EMEF.csv', sep=';', header=0, encoding='latin-1')
EMEF.head()

IDENT    FECHAINI   HORAINI  HORAINI_H  HORAINI_M  HORAINI_S    FECHAFIN  \
0   10.0  15/11/2018  18:44:43         18         44         43  26/11/2018   
1   11.0  13/12/2018  16:59:13         16         59         13  13/12/2018   
2   12.0  11/12/2018  13:28:01         13         28          1  12/12/2018   
3   31.0  06/11/2018  16:21:21         16         21         21  06/11/2018   
4   51.0  05/12/2018  12:10:14         12         10         14  05/12/2018   

    HORAFIN  HORAFIN_H  HORAFIN_M   ...    ESTRAT_COD                 ESTRAT  \
0  13:44:21         13         44   ...             1  Barcelona Districte 1   
1  17:15:09         17         15   ...             1  Barcelona Districte 1   
2  13:45:15         13         45   ...             1  Barcelona Districte 1   
3  16:40:02         16         40   ...             1  Barcelona Districte 1   
4  17:58:02         17         58   ...             1  Barcelona Districte 1   

  SEXE_COD  SEXE ANYNAIX  EDAT GR_EDAT_COD  GR_EDAT METODE_COD  METODE  
0        1  Home    1993    24           1    16-29          2    CAPI  
1        1  Home    1991    26           1    16-29          2    CAPI  
2        1  Home    2000    18           1    16-29          2    CAPI  
3        1  Home    1991    26           1    16-29          1    CATI  
4        1  Home    1991    27           1    16-29          2    CAPI  

[5 rows x 25 columns]

In [3]:
EMEF.index

RangeIndex(start=0, stop=10162, step=1)

In [4]:
EMEF.describe()

IDENT     HORAINI_H     HORAINI_M     HORAINI_S     HORAFIN_H  \
count  10162.000000  10162.000000  10162.000000  10162.000000  10162.000000   
mean      55.672806     15.897068     31.370006     29.430427     15.884570   
std       61.844734      2.724468     17.147274     17.194881      3.182436   
min        1.001000      0.000000      0.000000      0.000000      0.000000   
25%       26.243250     14.000000     17.000000     15.000000     14.000000   
50%       51.477000     16.000000     32.000000     29.000000     16.000000   
75%       76.738000     18.000000     46.000000     44.000000     19.000000   
max      990.000000     23.000000     59.000000     59.000000     23.000000   

          HORAFIN_M     HORAFIN_S   N_DIA_S_COD     CMUNI_COD    ESTRAT_COD  \
count  10162.000000  10162.000000  10162.000000  10162.000000  10162.000000   
mean      29.656564     29.258906      3.452076   8545.796694     35.466542   
std       17.343759     17.345519      1.571357   3548.672258     22.273097   
min        0.000000      0.000000      1.000000   8001.000000      1.000000   
25%       15.000000     14.000000      2.000000   8019.000000     12.000000   
50%       30.000000     29.000000      3.000000   8114.000000     37.000000   
75%       45.000000     44.000000      5.000000   8218.000000     56.000000   
max       59.000000     59.000000      7.000000  43163.000000     71.000000   

           SEXE_COD       ANYNAIX          EDAT   GR_EDAT_COD    METODE_COD  
count  10162.000000  10162.000000  10162.000000  10162.000000  10162.000000  
mean       1.515154   1970.051860     47.818736      2.598209      1.436922  
std        0.499795     17.108624     17.102665      1.009379      1.342750  
min        1.000000   1924.000000     16.000000      1.000000      1.000000  
25%        1.000000   1956.000000     36.000000      2.000000      1.000000  
50%        2.000000   1971.000000     47.000000      3.000000      1.000000  
75%        2.000000   1982.000000     62.000000      3.000000      1.000000  
max        2.000000   2002.000000     94.000000      4.000000      6.000000

In [5]:
EMEF.dtypes

IDENT          float64
FECHAINI        object
HORAINI         object
HORAINI_H        int64
HORAINI_M        int64
HORAINI_S        int64
FECHAFIN        object
HORAFIN         object
HORAFIN_H        int64
HORAFIN_M        int64
HORAFIN_S        int64
N_DIA_S_COD      int64
N_DIA_S         object
CMUNI_COD        int64
CMUNI           object
ESTRAT_COD       int64
ESTRAT          object
SEXE_COD         int64
SEXE            object
ANYNAIX          int64
EDAT             int64
GR_EDAT_COD      int64
GR_EDAT         object
METODE_COD       int64
METODE          object
dtype: object

In [6]:
EMEF.columns

Index(['IDENT', 'FECHAINI', 'HORAINI', 'HORAINI_H', 'HORAINI_M', 'HORAINI_S',
       'FECHAFIN', 'HORAFIN', 'HORAFIN_H', 'HORAFIN_M', 'HORAFIN_S',
       'N_DIA_S_COD', 'N_DIA_S', 'CMUNI_COD', 'CMUNI', 'ESTRAT_COD', 'ESTRAT',
       'SEXE_COD', 'SEXE', 'ANYNAIX', 'EDAT', 'GR_EDAT_COD', 'GR_EDAT',
       'METODE_COD', 'METODE'],
      dtype='object')

In [7]:
EMEF.shape

(10162, 25)

In [8]:
EMEF.isnull().sum(axis=0)

IDENT          0
FECHAINI       0
HORAINI        0
HORAINI_H      0
HORAINI_M      0
HORAINI_S      0
FECHAFIN       0
HORAFIN        0
HORAFIN_H      0
HORAFIN_M      0
HORAFIN_S      0
N_DIA_S_COD    0
N_DIA_S        0
CMUNI_COD      0
CMUNI          0
ESTRAT_COD     0
ESTRAT         0
SEXE_COD       0
SEXE           0
ANYNAIX        0
EDAT           0
GR_EDAT_COD    0
GR_EDAT        0
METODE_COD     0
METODE         0
dtype: int64

# Model de predicció hora de trucada

In [9]:
X = EMEF[['CMUNI_COD', 'ESTRAT_COD', 'SEXE_COD', 'ANYNAIX', 'EDAT', 'GR_EDAT_COD']]
y = EMEF[['HORAFIN_H']]

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [11]:
X_val, X_test, y_val, y_test = train_test_split(X_test, y_test, test_size=0.5)

In [12]:
X_train.shape

(8129, 6)

In [13]:
X_test.shape

(1017, 6)

In [14]:
X_val.shape

(1016, 6)

### Classificador Gradient Boosting

In [15]:
grd = GradientBoostingClassifier(n_estimators=50, max_depth=2,
                             random_state=0, min_samples_leaf=20, learning_rate = 0.01)

In [16]:
grd.fit(X_train, y_train)

C:\Users\Lau\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.01, loss='deviance', max_depth=2,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=20, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=50,
              presort='auto', random_state=0, subsample=1.0, verbose=0,
              warm_start=False)

In [17]:
grd.score(X_val, y_val)

0.11515748031496063

In [18]:
grd.score(X_train, y_train)

0.12350842662074056

##### El score en los datos de train y los de validación se acercan

In [19]:
grd.score(X_test, y_test)

0.11012782694198624

##### El modelo tiene una precisión de 0,11

In [20]:
a = X_test.sample()
a

CMUNI_COD  ESTRAT_COD  SEXE_COD  ANYNAIX  EDAT  GR_EDAT_COD
3902       8072          27         1     1995    23            1

In [21]:
grd.predict(a)

array([19], dtype=int64)

In [22]:
df = pd.DataFrame({'CMUNI_COD':[8072], 'ESTRAT_COD':[27], 'SEXE_COD':[1], 'ANYNAIX':[1995], 'EDAT':[23], 'GR_EDAT_COD':[1]})

In [23]:
df

CMUNI_COD  ESTRAT_COD  SEXE_COD  ANYNAIX  EDAT  GR_EDAT_COD
0       8072          27         1     1995    23            1

In [24]:
grd.predict(df)

array([19], dtype=int64)

In [25]:
grd.predict(X_test).mean()

17.644051130776795

In [26]:
grd.predict(X_test)

array([19, 18, 15, ..., 18, 18, 18], dtype=int64)

In [27]:
df_3 = X_test.copy()

In [28]:
df_3.head()

CMUNI_COD  ESTRAT_COD  SEXE_COD  ANYNAIX  EDAT  GR_EDAT_COD
342        8019           2         2     1979    39            2
8642       8192          61         2     1996    22            1
1045       8019           5         2     1947    71            4
3554       8221          25         2     1981    37            2
7053       8279          52         1     1988    30            2

In [29]:
df_3['HORAFIN_H'] = grd.predict(X_test)

In [30]:
df_3.head()

CMUNI_COD  ESTRAT_COD  SEXE_COD  ANYNAIX  EDAT  GR_EDAT_COD  HORAFIN_H
342        8019           2         2     1979    39            2         19
8642       8192          61         2     1996    22            1         18
1045       8019           5         2     1947    71            4         15
3554       8221          25         2     1981    37            2         18
7053       8279          52         1     1988    30            2         18

In [33]:
df_3[(df_3['SEXE_COD'] == 1) & (df_3['GR_EDAT_COD'] == 2) & (df_3['ESTRAT_COD'] == 5)]['HORAFIN_H'].mean()

19.0

In [34]:
result = df_3.groupby(by = ['ESTRAT_COD','SEXE_COD', 'GR_EDAT_COD'])['HORAFIN_H'].mean()
result

ESTRAT_COD  SEXE_COD  GR_EDAT_COD
1           1         1              17.000000
                      2              19.000000
                      3              19.000000
                      4              14.500000
            2         1              19.000000
                      2              19.000000
                      3              16.333333
                      4              15.333333
2           1         1              19.000000
                      2              19.000000
                      3              18.000000
                      4              15.000000
            2         1              19.000000
                      2              19.000000
                      3              18.200000
                      4              15.000000
3           1         1              19.000000
                      2              19.000000
                      3              19.000000
                      4              15.000000
            2         1   

In [35]:
result.to_csv('Trucades_EMEF.csv', sep=';', header=1, encoding='latin-1')

In [36]:
result.to_excel('Trucades_EMEF.xlsx', sheet_name='Resultat')

In [132]:
df_3.groupby(by = ['ESTRAT_COD','SEXE_COD', 'GR_EDAT_COD'])['HORAFIN_H'].count()

ESTRAT_COD  SEXE_COD  GR_EDAT_COD
1           1         1               2
                      2               2
                      3               2
                      4               2
            2         1               2
                      2               2
                      3               1
2           1         1               3
                      2               5
                      3               4
                      4              10
            2         1               1
                      2               8
                      3               8
                      4               3
3           1         2               3
                      3               6
                      4               2
            2         1               2
                      2               4
                      3               5
                      4               3
4           1         2               1
                      3               2
      

In [135]:
df_3[(df_3['SEXE_COD'] == 1) & (df_3['GR_EDAT_COD'] == 4) & (df_3['ESTRAT_COD'] == 2)]['HORAFIN_H']

271    19
291    15
293    15
295    15
300    15
277    17
283    15
290    15
272    15
294    15
Name: HORAFIN_H, dtype: int64

In [140]:
df_3[(df_3['SEXE_COD'] == 1) & (df_3['GR_EDAT_COD'] == 4) & (df_3['ESTRAT_COD'] == 2)]['HORAFIN_H'].mean()

15.6

In [148]:
df_3[(df_3['SEXE_COD'] == 2) & (df_3['GR_EDAT_COD'] == 1) & (df_3['ESTRAT_COD'] == 1)]['HORAFIN_H']

72    15
78    17
Name: HORAFIN_H, dtype: int64

In [149]:
df_3[(df_3['SEXE_COD'] == 2) & (df_3['GR_EDAT_COD'] == 1) & (df_3['ESTRAT_COD'] == 1)]['HORAFIN_H'].mean()

16.0